library('dplyr')
library('data.table')
library('lubridate')
set.seed(123)
library('randomForest')
library('tidyverse')
library('stringr')
library('shinydashboard')
library('plotly')
library('shiny')
library('shinyjs')
library("DT")
library('dplyr')
library('markdown')
library('tidyr')

dat <- read_csv("data.csv")
